//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO
    {
        public long ConMaestro { get; set; }
        public long ConUsuario { get; set; }
        public decimal TotalFactura { get; set; }
        public System.DateTime FechaCompra { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
