//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public long ConProducto { get; set; }
        public Nullable<long> ConModelo { get; set; }
        public Nullable<long> ConMarca { get; set; }
        public Nullable<long> ConCategoria { get; set; }
        public decimal Precio { get; set; }
        public long Stock { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MODELO MODELO { get; set; }
    }
}
